### ISSUE TITLE
.　

### ISSUE THREAD

**Issue by 1LUXION** [byongshintv/dcconbundle#1]

**Comment by byongshintv** [comment]
무슨 언어 쓰는데

**Comment by yaj0928** [comment]
> 무슨 언어 쓰는데

형 나도 코드좀

**Comment by WwLSJwW** [comment]
C# js 파이썬 등등 쓰긴하는데 그냥 형이 작업한걸로 줘도 돼 새로운 언어여도 괜찮우니까

**Comment by yaj0928** [comment]
나도 마찬가지
cy8er@staycute.xyz

**Comment by WwLSJwW** [comment]
우효~☆ 병신사마노 코드 GET또다제~
5252! 이정도라면 플밍대회 최상위권 아니냐곳?!(쑿)
illusion10601@gmail.com

**Comment by gwak1635** [comment]
형 나도
gwak1635@gmail.com

**Comment by ghost** [comment]
@)))))))

me@spt.tf
